struct stat;
struct rtcdate;

// system calls
int fork(void);
int exit(void) __attribute__((noreturn));
int wait(void);
int pipe(int*);
int write(int, const void*, int);
int read(int, void*, int);
int close(int);
int kill(int);
int exec(char*, char**);
int open(const char*, int);
int mknod(const char*, short, short);
int unlink(const char*);
int fstat(int fd, struct stat*);
int link(const char*, const char*);
int mkdir(const char*);
int chdir(const char*);
int dup(int);
int getpid(void);
char* sbrk(int);
int sleep(int);
int uptime(void);
// int inc_num(int);
int invoked_syscalls(int pid);
int sort_syscalls(int pid);
int get_count(int pid, int sysNum);
int log_syscalls(void);
int releasesleep_syscalls(void);
int acquiresleep_syscalls(void);
int ticketlockinit(void);
int ticketlocktest(void);
int rwinit(void);
int rwtest(uint pattern);

// ulib.c
int stat(const char*, struct stat*);
char* strcpy(char*, const char*);
char* strnconcat(char* os, const char*cs, int n);
void *memmove(void*, const void*, int);
char* strchr(const char*, char c);
int strcmp(const char*, const char*);
void printf(int, const char*, ...);
char* gets(char*, int max);
uint strlen(const char*);
void* memset(void*, int, uint);
void* malloc(uint);
void free(void*);
int atoi(const char*);
char* itoa_simple_helper(char *dest, int i);
char* itoa_simple(char *dest, int i);
